driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: fedora-25
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-chef-12
    driver_config:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12
    transport:
      username: ubuntu

suites:
- name: system_ruby
  run_list:
  - recipe[apt]
  - recipe[ruby_build]
  - recipe[ruby_rbenv::system]
  attributes:
    rbenv:
      plugins:
      - name: rbenv-vars
        git_url: https://github.com/sstephenson/rbenv-vars.git
      rubies:
      - name: 2.1.6
        environment:
          CONFIGURE_OPTS: --disable-install-rdoc
      - name: 2.4.1
        environment:
          CONFIGURE_OPTS: --disable-install-rdoc
      global: 2.1.6
      gems:
        '2.4.1':
          - name: bundler
            action: upgrade
