# frozen_string_literal: true

name              'ruby_rbenv'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
issues_url        'https://github.com/sous-chefs/ruby_rbenv/issues'
source_url        'https://github.com/sous-chefs/ruby_rbenv'
license           'Apache-2.0'
description       'Manages rbenv and installs Rbenv based Rubies'
version           '5.0.24'
chef_version      '>= 16.0'

depends 'yum-almalinux'

supports 'almalinux'
supports 'amazon'
supports 'centos_stream'
supports 'debian'
supports 'fedora'
supports 'mac_os_x'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'rocky'
supports 'ubuntu'
