name              'ruby_rbenv'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
issues_url        'https://github.com/sous-chefs/ruby_rbenv/issues'
source_url        'https://github.com/sous-chefs/ruby_rbenv'
license           'Apache-2.0'
description       'Manages rbenv and installs Rbenv based Rubies'
version           '5.0.11'
chef_version      '>= 16.0'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'linuxmint'
supports 'mac_os_x'
supports 'opensuse'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
